# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WILU 2020
subtitle: "something about the future"
#email: youremailaddress@gmail.com
#description: The Jekyll version of the Massively theme by HTML5 UP.
#baseurl: "/massively-jekyll-theme" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wilu-conference.github.io/" # the base hostname & protocol for your site

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github: wilu-conference
twitter: mytwittername
facebook: myfacebook
instagram: myinstagram

# Build settings
markdown: kramdown

#paginate: 6
#paginate_path: /page:num/

include:
  - _pages
  - _posts

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - massively_jekyll_theme.gemspec
  - _site/

compress_html:
  clippings: []
  blanklines: false
  comments: all
  

